### ISSUE TITLE
How to generate pickle files

### ISSUE THREAD

**Issue by warmth27** [jiayingwu19/Prompt-and-Align#1]
Hello, I would like to know how the pickle file is generated. I tried to regenerate the pickle but failed. Could you please share the implementation code? Thank you very much.

**Comment by jiayingwu19** [comment]
Hello, thanks for your interest in our work.

We have uploaded our data pre-processing script at `Process/adj_matrix_fewshot.py`, and updated the README file with the corresponding instructions under "Constructing the News Proximity Graph from the Raw Social Context". Please refer to these updates to generate the pickle files, which contain the normalized adjacency matrices.

We hope this addresses your question.
